const $ = (id) => document.getElementById(id);
const money = (n) => `${Number(n ?? 0) < 0 ? "-" : ""}$${Math.abs(Number(n ?? 0)).toFixed(2)}`;
const compact = (n) => Number(n ?? 0) >= 1e6 ? `$${(n / 1e6).toFixed(1)}M` : Number(n ?? 0) >= 1e3 ? `$${(n / 1e3).toFixed(1)}K` : `$${Number(n ?? 0).toFixed(0)}`;
const esc = (v) => String(v ?? "").replace(/[&<>"']/g, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
const clock = (v) => v ? new Date(v).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit",second:"2-digit"}) : "--";
const scoreClass = (n) => Number(n) >= 75 ? "high" : Number(n) >= 55 ? "mid" : "low";
const decisionClass = (d) => d === "LIVE_ELIGIBLE" ? "live" : d === "ALERT" ? "alert" : "reject";
const decisionText = (d) => d === "LIVE_ELIGIBLE" ? "可交易" : d === "ALERT" ? "观察" : "拦截";
function render(data){const s=data.summary??{};$("candidates").textContent=s.candidates??0;$("assessments").textContent=s.assessments??0;$("openPaper").textContent=s.openPaper??0;$("pnl").textContent=money(s.realizedPnlUsd);$("pnl").className=Number(s.realizedPnlUsd??0)<0?"negative":"positive";$("updated").textContent=clock(Date.now());const a=data.assessments??[];$("feedCount").textContent=`${a.length} 条`;$("rows").innerHTML=a.length?a.map((x)=>{const c=x.candidate??{},m=c.market??{},r=(x.reasons??[]).join(" · ");return `<tr><td><div class="token"><strong>${esc(c.symbol)}</strong><small>${esc(c.name)} · ${esc(c.mint)}</small></div></td><td><span class="score ${scoreClass(x.score)}">${x.score}</span></td><td>${compact(m.liquidityUsd)}</td><td>${m.buys5m??0} / ${m.sells5m??0}</td><td>${compact(m.volume24hUsd)}</td><td><span class="decision ${decisionClass(x.decision)}">${decisionText(x.decision)}</span></td><td class="reasons" title="${esc(r)}">${esc(r||"无")}</td></tr>`}).join(""):`<tr><td colspan="7" class="empty">还没有评分记录。</td></tr>`;const p=data.paperPositions??[];$("positions").innerHTML=p.length?p.slice(0,8).map((x)=>`<div class="position"><div class="row"><strong>${esc(x.symbol)}</strong><span class="${Number(x.pnlUsd??0)<0?"negative":"positive"}">${x.status==="OPEN"?"OPEN":money(x.pnlUsd)}</span></div><div class="meta">投入 ${money(x.investedUsd)} · 入场 ${money(x.entryPriceUsd)}</div></div>`).join(""):`<div class="empty">暂无纸上仓位</div>`;const ev=data.audit??[];$("audit").innerHTML=ev.length?ev.slice(0,8).map((x)=>`<div class="audit-item"><div class="row"><span class="audit-event">${esc(x.eventType)}</span><span class="meta">${clock(x.createdAt)}</span></div><div class="meta">${esc(JSON.stringify(x.payload??{}))}</div></div>`).join(""):`<div class="empty">暂无审计事件</div>`}
async function refresh(){try{const r=await fetch("/api/dashboard",{cache:"no-store"});if(!r.ok)throw Error(`HTTP ${r.status}`);render(await r.json());$("error").hidden=true;$("dot").className="ok";$("connection").textContent="实时连接"}catch(e){$("error").hidden=false;$("error").textContent=`无法读取仪表盘：${e.message}`;$("dot").className="error";$("connection").textContent="连接失败"}}
$("refresh").addEventListener("click",refresh);new ResizeObserver(()=>document.body.dataset.resized="true").observe(document.body);refresh();setInterval(refresh,5000);
